# Generated by Django 4.2.25 on 2025-11-04 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField()),
                ('time_slot', models.CharField(choices=[('11:00 AM', '11:00 AM'), ('11:15 AM', '11:15 AM'), ('11:30 AM', '11:30 AM'), ('11:45 AM', '11:45 AM'), ('12:00 PM', '12:00 PM'), ('12:15 PM', '12:15 PM'), ('12:30 PM', '12:30 PM'), ('12:45 PM', '12:45 PM'), ('1:00 PM', '1:00 PM'), ('1:15 PM', '1:15 PM'), ('1:30 PM', '1:30 PM'), ('1:45 PM', '1:45 PM'), ('2:00 PM', '2:00 PM'), ('2:15 PM', '2:15 PM'), ('2:30 PM', '2:30 PM'), ('2:45 PM', '2:45 PM'), ('3:00 PM', '3:00 PM'), ('3:15 PM', '3:15 PM'), ('3:30 PM', '3:30 PM'), ('3:45 PM', '3:45 PM'), ('4:00 PM', '4:00 PM'), ('4:15 PM', '4:15 PM'), ('4:30 PM', '4:30 PM'), ('4:45 PM', '4:45 PM'), ('5:00 PM', '5:00 PM'), ('5:15 PM', '5:15 PM'), ('5:30 PM', '5:30 PM'), ('5:45 PM', '5:45 PM'), ('6:00 PM', '6:00 PM'), ('6:15 PM', '6:15 PM'), ('6:30 PM', '6:30 PM'), ('6:45 PM', '6:45 PM'), ('7:00 PM', '7:00 PM'), ('7:15 PM', '7:15 PM'), ('7:30 PM', '7:30 PM'), ('7:45 PM', '7:45 PM'), ('8:00 PM', '8:00 PM'), ('8:15 PM', '8:15 PM'), ('8:30 PM', '8:30 PM'), ('8:45 PM', '8:45 PM'), ('9:00 PM', '9:00 PM'), ('9:15 PM', '9:15 PM'), ('9:30 PM', '9:30 PM'), ('9:45 PM', '9:45 PM'), ('10:00 PM', '10:00 PM'), ('10:15 PM', '10:15 PM'), ('10:30 PM', '10:30 PM'), ('10:45 PM', '10:45 PM'), ('11:00 PM', '11:00 PM')], max_length=10)),
                ('number_of_guests', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reservation_date', 'time_slot'],
            },
        ),
    ]
