# Generated by Django 4.2.25 on 2025-11-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menuitem_options_alter_menuitem_category'),
        ('reserve', '0002_alter_reservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='allergen',
            field=models.ManyToManyField(blank=True, to='menu.allergen'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.CharField(choices=[('10:00 AM', '10:00 AM'), ('10:15 AM', '10:15 AM'), ('10:30 AM', '10:30 AM'), ('10:45 AM', '10:45 AM'), ('11:00 AM', '11:00 AM'), ('11:15 AM', '11:15 AM'), ('11:30 AM', '11:30 AM'), ('11:45 AM', '11:45 AM'), ('12:00 PM', '12:00 PM'), ('12:15 PM', '12:15 PM'), ('12:30 PM', '12:30 PM'), ('12:45 PM', '12:45 PM'), ('1:00 PM', '1:00 PM'), ('1:15 PM', '1:15 PM'), ('1:30 PM', '1:30 PM'), ('1:45 PM', '1:45 PM'), ('2:00 PM', '2:00 PM'), ('2:15 PM', '2:15 PM'), ('2:30 PM', '2:30 PM'), ('2:45 PM', '2:45 PM'), ('3:00 PM', '3:00 PM'), ('3:15 PM', '3:15 PM'), ('3:30 PM', '3:30 PM'), ('3:45 PM', '3:45 PM'), ('4:00 PM', '4:00 PM'), ('4:15 PM', '4:15 PM'), ('4:30 PM', '4:30 PM'), ('4:45 PM', '4:45 PM'), ('5:00 PM', '5:00 PM'), ('5:15 PM', '5:15 PM'), ('5:30 PM', '5:30 PM'), ('5:45 PM', '5:45 PM'), ('6:00 PM', '6:00 PM'), ('6:15 PM', '6:15 PM'), ('6:30 PM', '6:30 PM'), ('6:45 PM', '6:45 PM'), ('7:00 PM', '7:00 PM'), ('7:15 PM', '7:15 PM'), ('7:30 PM', '7:30 PM'), ('7:45 PM', '7:45 PM'), ('8:00 PM', '8:00 PM'), ('8:15 PM', '8:15 PM'), ('8:30 PM', '8:30 PM'), ('8:45 PM', '8:45 PM'), ('9:00 PM', '9:00 PM'), ('9:15 PM', '9:15 PM'), ('9:30 PM', '9:30 PM'), ('9:45 PM', '9:45 PM'), ('10:00 PM', '10:00 PM'), ('10:15 PM', '10:15 PM'), ('10:30 PM', '10:30 PM'), ('10:45 PM', '10:45 PM'), ('11:00 PM', '11:00 PM')], max_length=10),
        ),
    ]
