# Generated by Django 4.2.25 on 2025-11-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_reservation_allergen_alter_reservation_time_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='allergen',
            new_name='allergies',
        ),
    ]
