# Generated by Django 5.2.8 on 2025-11-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_reservation_guest_email_reservation_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
