# Generated by Django 5.2.8 on 2025-11-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_alter_reservation_guest_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_date', 'time_slot']},
        ),
    ]
