# Generated by Django 5.2.8 on 2025-11-11 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0008_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(default=0, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-\\(\\)]{7,20}$', 'Enter a valid phone number (digits, spaces, +, - allowed).')]),
            preserve_default=False,
        ),
    ]
