# Generated by Django 5.2.8 on 2025-11-17 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0009_alter_reservation_guest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(default='example guest', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-\\(\\)]{7,20}$', 'Please enter a valid phone number')]),
        ),
    ]
