# Generated by Django 4.2.25 on 2025-11-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Entree', 'Entree'), ('Main', 'Main Course'), ('Side', 'Side Dish'), ('Dessert', 'Dessert'), ('Beverage', 'Beverage')], max_length=50)),
                ('name', models.TextField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
