# Generated by Django 4.2.25 on 2025-11-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_category_alter_menuitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allergen',
            field=models.CharField(blank=True, choices=[('Celery', 'Celery'), ('Cereals', 'Cereals containing gluten'), ('Crustaceans', 'Crustaceans'), ('Eggs', 'Eggs'), ('Fish', 'Fish'), ('Lupin', 'Lupin'), ('Milk', 'Milk'), ('Molluscs', 'Molluscs'), ('Mustard', 'Mustard'), ('Nuts', 'Nuts'), ('Peanuts', 'Peanuts'), ('Sesame', 'Sesame seeds'), ('Soya', 'Soya'), ('Sulphites', 'Sulphur dioxide and sulphites')], max_length=50),
        ),
    ]
