# Generated by Django 4.2.25 on 2025-11-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_allergen_remove_menuitem_allergen_menuitem_allergen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
