# Generated by Django 4.2.25 on 2025-11-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_allergen_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Entree', 'Entree'), ('Main', 'Main Course'), ('Side', 'Side Dish'), ('Dessert', 'Dessert'), ('Tasting', 'Tasting Menu')], max_length=50),
        ),
    ]
