# Generated by Django 4.2.25 on 2025-11-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menuitem_options_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='tasting_order',
            field=models.PositiveIntegerField(blank=True, help_text='Order for tasting menu', null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('a_la_carte', 'À la Carte'), ('tasting', 'Tasting Menu')], max_length=100),
        ),
    ]
