# Generated by Django 4.2.25 on 2025-11-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menuitem_tasting_order_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Entree', 'Entree'), ('Main', 'Main Course'), ('Side', 'Side Dish'), ('Dessert', 'Dessert'), ('Tasting', 'Tasting Menu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='tasting_order',
            field=models.PositiveIntegerField(blank=True, help_text='Order for tasting menu (1 = first course)', null=True),
        ),
    ]
