# Generated by Django 4.2.25 on 2025-11-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dietary_preferences',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
